controller_manager:
  ros__parameters:
    update_rate: 100    # in Hz

    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

mecanum_drive_controller:
  ros__parameters:

    front_left_wheel_command_joint_name: 'front_left_joint'
    front_right_wheel_command_joint_name: 'front_right_joint'
    rear_left_wheel_command_joint_name: 'back_left_joint'
    rear_right_wheel_command_joint_name: 'back_right_joint'

    kinematics:
      wheels_radius: 0.0325
      sum_of_robot_center_projection_on_X_Y_axis: 0.329
    
    base_frame_id: 'base_link'
    odom_frame_id: 'odom'
    use_stamped_vel: false
    enable_odom_tf: true
    cmd_vel_timeout: 0.5
    publish_rate: 50

